import * as tf from '@tensorflow/tfjs';
import * as cocoSsd from '@tensorflow-models/coco-ssd';
import { CategoryType, DetectionQualityStatus } from '../types';

export interface DetectionResult { class_id:number; class_name:string; category:CategoryType; confidence:number; x1:number; y1:number; x2:number; y2:number; tracking_id:number; timestamp:string; frame_number:number; }
export type AIEngineStatus='INITIALIZING'|'ACTIVE'|'DEGRADED'|'ERROR'|'NOT_READY';
export interface DiagnosticsData { modelName:string; modelStatus:AIEngineStatus; device:string; inputResolution:string; inferenceResolution:string; inferenceFps:number; cameraFps:number; lastInferenceMs:number; totalDetectionsCurrentFrame:number; currentCounts:{person:number;car:number;bicycle:number;camera:number}; uniqueTrackedCounts:{person:number;car:number;bicycle:number;camera:number}; trackingMethod:string; recentLogs:string[]; }
export interface EngineTestResult { modelLoaded:boolean; frameCaptured:boolean; inferenceSuccess:boolean; device:string; inferenceTimeMs:number; detectedCount:number; detections:{class_name:string;confidence:number;bbox:[number,number,number,number]}[]; timestamp:string; }
interface InternalTrack { id:number; category:CategoryType; class_name:string; bbox:[number,number,number,number]; confidence:number; lastSeenFrame:number; hits:number; }
type Source=HTMLVideoElement|HTMLCanvasElement|HTMLImageElement;

class RealDetectionService {
 private model:cocoSsd.ObjectDetection|null=null; private isModelLoading=false; private engineStatus:AIEngineStatus='INITIALIZING'; private statusMessage='Initializing AI Engine...'; private deviceName='Detecting...'; private nextTrackId=1; private activeTracks:InternalTrack[]=[]; private uniqueCategoryTrackIds={person:new Set<number>(),car:new Set<number>(),bicycle:new Set<number>(),camera:new Set<number>()}; private lastInferenceTimeMs=0; private inferenceFrameTimes:number[]=[]; private diagnosticLogs:string[]=[]; private isInferenceRunning=false;
 constructor(){this.initModel();}
 async initModel(){if(this.model)return true;if(this.isModelLoading)return false;this.isModelLoading=true;this.engineStatus='INITIALIZING';this.statusMessage='Loading Real Neural Network...';this.addLog('Initializing TensorFlow.js neural inference backend...');try{await tf.ready();const backend=tf.getBackend();this.deviceName=backend==='webgl'?'WebGL (GPU Acceleration)':backend==='wasm'?'WASM (CPU)':`${backend.toUpperCase()} (CPU)`;this.addLog(`TFJS Backend initialized: ${this.deviceName}`);this.model=await cocoSsd.load({base:'mobilenet_v2'});this.engineStatus='ACTIVE';this.statusMessage='AI Engine Active (Real Inference)';this.addLog('COCO-SSD MobileNetV2 loaded.');return true;}catch(e:any){this.engineStatus='ERROR';this.statusMessage=`Model Load Error: ${e?.message||'Failed'}`;this.addLog(`FATAL: ${this.statusMessage}`);return false;}finally{this.isModelLoading=false;}}
 getStatus(){return{status:this.engineStatus,message:this.statusMessage,device:this.deviceName};} isReady(){return !!this.model&&this.engineStatus==='ACTIVE';}
 mapCategory(c:string):CategoryType|null{const x=c.toLowerCase().trim();if(x==='person')return'person';if(x==='car'||x==='truck'||x==='bus')return'car';if(x==='bicycle')return'bicycle';return null;}
 async detectFrame(source:Source,frameNumber:number,threshold=0.4):Promise<DetectionResult[]>{if(!this.model||this.engineStatus!=='ACTIVE'||this.isInferenceRunning)return[];this.isInferenceRunning=true;const t0=performance.now();try{const raw=await this.model.detect(source as any);this.lastInferenceTimeMs=Math.round(performance.now()-t0);const now=performance.now();this.inferenceFrameTimes.push(now);if(this.inferenceFrameTimes.length>30)this.inferenceFrameTimes.shift();const w=source instanceof HTMLVideoElement?source.videoWidth:source instanceof HTMLImageElement?source.naturalWidth:source.width;const h=source instanceof HTMLVideoElement?source.videoHeight:source instanceof HTMLImageElement?source.naturalHeight:source.height;const valid=raw.map(p=>{const category=this.mapCategory(p.class);const score=Number(p.score);const [x,y,bw,bh]=p.bbox;return{category,class_name:p.class,confidence:score,bbox:[Math.max(0,Math.min(w,x)),Math.max(0,Math.min(h,y)),Math.max(0,Math.min(w,x+bw)),Math.max(0,Math.min(h,y+bh))] as [number,number,number,number]};}).filter(d=>d.category&&d.confidence>=threshold&&d.confidence<=1&&d.bbox[2]>d.bbox[0]&&d.bbox[3]>d.bbox[1]) as {category:CategoryType;class_name:string;confidence:number;bbox:[number,number,number,number]}[];const result=this.updateSpatialTracker(valid,frameNumber);this.isInferenceRunning=false;return result;}catch(e){this.addLog(`Inference error: ${e instanceof Error?e.message:String(e)}`);this.isInferenceRunning=false;return[];}}
 private updateSpatialTracker(dets:{category:CategoryType;class_name:string;confidence:number;bbox:[number,number,number,number]}[],frame:number){const timestamp=new Date().toLocaleTimeString('en-GB');const matched=new Set<number>();const out:DetectionResult[]=[];for(const d of dets){let best=.3,idx=-1;for(let i=0;i<this.activeTracks.length;i++){const t=this.activeTracks[i];if(matched.has(i)||t.category!==d.category)continue;const iou=this.iou(d.bbox,t.bbox);if(iou>best){best=iou;idx=i;}}let id;if(idx>=0){matched.add(idx);const t=this.activeTracks[idx];t.bbox=d.bbox;t.confidence=d.confidence;t.lastSeenFrame=frame;t.hits++;id=t.id;}else{id=this.nextTrackId++;this.activeTracks.push({id,category:d.category,class_name:d.class_name,bbox:d.bbox,confidence:d.confidence,lastSeenFrame:frame,hits:1});this.uniqueCategoryTrackIds[d.category].add(id);}out.push({class_id:id,class_name:d.class_name,category:d.category,confidence:d.confidence,x1:d.bbox[0],y1:d.bbox[1],x2:d.bbox[2],y2:d.bbox[3],tracking_id:id,timestamp,frame_number:frame});}this.activeTracks=this.activeTracks.filter(t=>frame-t.lastSeenFrame<20);return out;}
 private iou(a:[number,number,number,number],b:[number,number,number,number]){const l=Math.max(a[0],b[0]),t=Math.max(a[1],b[1]),r=Math.min(a[2],b[2]),bt=Math.min(a[3],b[3]);if(r<=l||bt<=t)return 0;const inter=(r-l)*(bt-t),u=(a[2]-a[0])*(a[3]-a[1])+(b[2]-b[0])*(b[3]-b[1])-inter;return u>0?inter/u:0;}
 async testAiEngine(source:Source):Promise<EngineTestResult>{const timestamp=new Date().toLocaleTimeString('en-GB');if(!this.model&&!(await this.initModel()))return{modelLoaded:false,frameCaptured:false,inferenceSuccess:false,device:this.deviceName,inferenceTimeMs:0,detectedCount:0,detections:[],timestamp};const t=performance.now();try{const p=await this.model!.detect(source as any);const detections=p.filter(x=>x.score>=.35&&this.mapCategory(x.class)!==null).map(x=>({class_name:x.class,confidence:x.score,bbox:x.bbox as [number,number,number,number]}));return{modelLoaded:true,frameCaptured:true,inferenceSuccess:true,device:this.deviceName,inferenceTimeMs:Math.round(performance.now()-t),detectedCount:detections.length,detections,timestamp};}catch{return{modelLoaded:true,frameCaptured:true,inferenceSuccess:false,device:this.deviceName,inferenceTimeMs:0,detectedCount:0,detections:[],timestamp};}}
 getDiagnostics(w=0,h=0,cameraFps=0):DiagnosticsData{const counts={person:0,car:0,bicycle:0,camera:0};for(const t of this.activeTracks)counts[t.category]++;const n=this.inferenceFrameTimes.length;const fps=n>=2?Math.round(1000*(n-1)/(this.inferenceFrameTimes[n-1]-this.inferenceFrameTimes[0])):0;return{modelName:'COCO-SSD MobileNetV2',modelStatus:this.engineStatus,device:this.deviceName,inputResolution:`${w}x${h}`,inferenceResolution:`${w}x${h}`,inferenceFps:fps,cameraFps:Number.isFinite(cameraFps)?cameraFps:0,lastInferenceMs:this.lastInferenceTimeMs,totalDetectionsCurrentFrame:this.activeTracks.length,currentCounts:counts,uniqueTrackedCounts:{person:this.uniqueCategoryTrackIds.person.size,car:this.uniqueCategoryTrackIds.car.size,bicycle:this.uniqueCategoryTrackIds.bicycle.size,camera:this.uniqueCategoryTrackIds.camera.size},trackingMethod:'IoU spatial tracking',recentLogs:[...this.diagnosticLogs]};}
 resetTracking(){this.nextTrackId=1;this.activeTracks=[];Object.values(this.uniqueCategoryTrackIds).forEach(s=>s.clear());}
 getQualityStatus():DetectionQualityStatus{return this.engineStatus==='ACTIVE'?'Good':'Poor Visibility';}
 private addLog(m:string){this.diagnosticLogs.push(`[${new Date().toLocaleTimeString('en-GB')}] ${m}`);if(this.diagnosticLogs.length>30)this.diagnosticLogs.shift();}
}
export const detectionService=new RealDetectionService();export default detectionService;
